import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "../styles/_reset-css.css";
import "./globals.css";
import Providers from "./providers";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // adjust based on what you need
  variable: "--font-roboto-mono", // optional, for use in CSS
  display: "swap", // optional for better UX
});

export const metadata: Metadata = {
  title: "Sunfil1 home page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`text-textPrimary`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
